# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Auto Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Yarn
      uses: mskelton/setup-yarn@v1.3.0
    - run: yarn
    - run: yarn build
    - name: Push changes
      uses: actions-go/push@v1
      with:
        commit-message: auto build
        force: true
